### ISSUE TITLE
How can I specify the IP address used for intitial certificate generation?

### ISSUE THREAD

**Issue by km6lslf** [Cloud-RF/tak-server#38]
![image](https://github.com/Cloud-RF/tak-server/assets/72669490/d49aed71-db64-43c4-8077-2e4e914e43b4)

The installer automatically selected the LAN IP of my VM, but I need it to use the public IPv4 address that I have access to. All appropriate ports are forwarded, so if it uses the IP address I can provide, it should work seamlessly. How can I make this work?

**Comment by km6lslf** [comment]
It looks like I may have solved the IP address issue by making changes to the "get IP" section of the setup script and the hostIP locations in CoreConfig.xml.

It's still throwing the Java error, though. I'll search for a solution to that now.

**Comment by modernham** [comment]
That IP address is for connecting to the database from the TAK server that is running on your local system. It should be the local address. You should probably change that back because it's configured to talk to itself. 

The IP also has nothing to do with certificate generation.
If you want to access it publicly, you only need to make sure your ports are open and forwarded to your servers LAN IP on the default configuration. If your server is behind a NAT such as a router, it has no use for a WAN IP.

**Comment by km6lslf** [comment]
Thanks for the tip!
