### ISSUE TITLE
running on macos under docker - the setup script keeps saying it is using port 9000 even though nothing is running on that port??

### ISSUE THREAD

**Issue by crupib** [Cloud-RF/tak-server#51]
# Environment

Please provide as much information as possible about your environment:

- Hardware Make/Model: Macos Pro x64
- Operating System and Version Mac Sonoma
- Docker Version (`docker -v`): 4.29.0 (145265)
- Docker Compose Version (`docker compose version`) or (`docker-compose version`): v2.26.1-desktop.1
- CPU Details (make/model and/or speed/core count): 2.4 GHz 8-Core Intel Core i9
- RAM (e.g. `free -h`): 32 GB 2400 MHz DDR4
- Disk Availability (e.g. `df -h`): 400GB
- TAK Server Version From TAK.gov: 5.1

# Description

# Steps to Reproduce

# Debug Output

**Comment by AlexWinder** [comment]
Closing this. No detail provided other than the title.

Feel free to add more details and reopen.

**Comment by crupib** [comment]
What other details do you need from me? It’s been over a month since you
have gotten back to me

bc
***@***.***

**Comment by AlexWinder** [comment]
For someone to resolve this then at the minimum it would need for the output of netstat and any console outputs which can help replicate the issues. 

The scripts have been written to catch the majority of known issues, if there is a bug in the scripts then we would need to know as much detail as possible, rather than just a single liner in the title. 

Please provide as much detail as possible that you feel would assist someone in solving this.
