### ISSUE TITLE
Different ports to acces docker containers?

### ISSUE THREAD

**Issue by NightFalcon650** [Cloud-RF/tak-server#55]
I want to install a tackserver via your script.
Is it possible to use other ports to acces the server container, for example not 8443:8443 but 28443:8443
This because some ports are allready used by other applications or because they are known ports.

Changing them in docker-compose.yml still throws a error while setting up.
If yes how can you do this without breaking the server

**Comment by AlexWinder** [comment]
I don't believe this is supported in the current iteration of this script. 

But you could, like you say, set the value in the `docker-compose.yaml`, but then the `setup.sh` script will need adjusting because this checks for ports which are in use. You can comment out the check which is done in the `setup.sh` script.

https://github.com/Cloud-RF/tak-server/blob/5a84032346f4a49d6b5ede7dfb7bf96bc6c8cfec/scripts/setup.sh#L135

**Comment by NightFalcon650** [comment]
Allready did that but then it throws this error line

 printf $info "No joy with DB at $IP, will retry in 10s. If this loops more than 6 times go and get some fresh air...\n"

**Comment by AlexWinder** [comment]
Actually, we document this in the [README.md](https://github.com/Cloud-RF/tak-server/blob/main/README.md). Those ports are required to be available.

https://github.com/Cloud-RF/tak-server/blob/5a84032346f4a49d6b5ede7dfb7bf96bc6c8cfec/README.md?plain=1#L117-L127

There may be ways to get it to run on other/non-standard ports but that would be best directed at the developers of TAK/TAK server.
